export const ADD_FOLLOWER = 'ADD_FOLLOWER';
export const ADDED_FOLLOWER = 'ADDED_FOLLOWER';
export const ADD_FOLLOWER_ERROR = 'ADD_FOLLOWER_ERROR';

export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GOT_FOLLOWERS = 'GOT_FOLLOWERS';
export const GET_FOLLOWERS_ERROR = 'GET_FOLLOWERS_ERROR';
