export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const GET_USER_MESSAGES = 'GET_USER_MESSAGES';
export const GOT_USER_MESSAGES = 'GOT_USER_MESSAGES';
export const GET_USER_MESSAGES_ERROR = 'GET_USER_MESSAGES_ERROR';
