export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const GET_USER_MESSAGES = 'GET_USER_MESSAGES';
export const GOT_USER_MESSAGES = 'GOT_USER_MESSAGES';
export const GET_USER_MESSAGES_ERROR = 'GET_USER_MESSAGES_ERROR';

export const GET_ACTIVE_USER_MESSAGES = 'GET_ACTIVE_USER_MESSAGES';
export const GOT_ACTIVE_USER_MESSAGES = 'GOT_ACTIVE_USER_MESSAGES';
export const GET_ACTIVE_USER_MESSAGES_ERROR = 'GET_ACTIVE_USER_MESSAGES_ERROR';

export const DELETE_USER_MESSAGE = 'DELETE_USER_MESSAGE';
export const DELETED_USER_MESSAGE = 'DELETED_USER_MESSAGE';
export const DELETE_USER_MESSAGE_ERROR = 'DELETE_USER_MESSAGE_ERROR';

export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GOT_ALL_MESSAGES = 'GOT_ALL_MESSAGES';
export const GET_ALL_MESSAGES_ERROR = 'GET_ALL_MESSAGES_ERROR';
