export const GET_USER = 'GET_USER';
export const GOT_USER = 'GOT_USER';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_SELECTED_PROFILE = 'GET_SELECTED_PROFILE';
export const GOT_SELECTED_PROFILE = 'GOT_SELECTED_PROFILE';
export const GET_SELECTED_PROFILE_ERROR = 'GET_SELECTED_PROFILE_ERROR';
